#
# Copyright (C) 2020,2022 Eclipse Foundation and others.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0.
#
# SPDX-FileType: DOCUMENTATION
# SPDX-FileCopyrightText: 2024 Ashish Kumar Singh
# SPDX-License-Identifier: Apache-2.0
#
name: Issue/PR response
permissions:
  issues: write
  pull-requests: write
on:
  issues:
    types:
      - opened
  pull_request_target:
    types:
      - opened
jobs:
  respond-to-issue:
    if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'renovate[bot]' && github.actor != 'githubactions[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Determine issue or PR number
        id: extract
        run: echo "NUMBER=${{ github.event.issue.number || github.event.pull_request.number }}" >> "$GITHUB_OUTPUT"

      - name: Respond to issue or PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ steps.extract.outputs.NUMBER }}
          body: >
            👋 Hi! Thank you for this contribution! Just to let you know, our HARMAN team does a round of issue and PR reviews every Monday and Friday! 
            Because you are a part of this community please feel free to comment, add to, or pick up any issues/PRs that are labled with `Status: Up for grabs`.
            You & others like you are the reason all of this works! So thank you & happy coding! 🚀
