#
# Copyright (C) 2020,2022 Eclipse Foundation and others.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0.
#
# SPDX-FileType: DOCUMENTATION
# SPDX-FileCopyrightText: 2024 Ashish Kumar Singh
# SPDX-License-Identifier: Apache-2.0
#
name: License Compliance

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read
  contents: write

jobs:
  check-licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Generate List of dependencies
        run: mvn verify dependency:list -s settings.xml -DskipTests -Dmaven.javadoc.skip=true -DappendOutput=true -DoutputFile=maven.deps
      - name: Run Eclipse Dash to generate DEPENDENCIES file
        run: java -jar eclipse-dash/org.eclipse.dash.licenses-1.1.1.jar maven.deps -summary DEPENDENCIES
      - name: Archive DEPENDENCIES file
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: LICENSE_INFO
          path: DEPENDENCIES
